# TODO: refactor to point at the model in the models/ directory
version: '3.3'
services:
  server:
    container_name: 'crayfish-tf-s'
    image: tensorflow/serving
    ports:
      - '8501:8501'
      - '8500:8500'
    volumes:
      - './models:/models'
    command:
      - '--model_config_file=/models/models.config'
      - '--model_config_file_poll_wait_seconds=60'
      - '--tensorflow_intra_op_parallelism=1'
      - '--tensorflow_inter_op_parallelism=1'
    cpuset: '0'
