// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/framework/resource_handle.proto

package org.tensorflow.framework;

/**
 * <pre>
 * Protocol buffer representing a handle to a tensorflow resource. Handles are
 * not valid across executions, but can be serialized back and forth from within
 * a single run.
 * </pre>
 * <p>
 * Protobuf type {@code tensorflow.ResourceHandle}
 */
public final class ResourceHandle extends
                                  com.google.protobuf.GeneratedMessageV3 implements
                                                                         // @@protoc_insertion_point(message_implements:tensorflow.ResourceHandle)
                                                                                 ResourceHandleOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use ResourceHandle.newBuilder() to construct.
    private ResourceHandle(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private ResourceHandle() {
        device_ = "";
        container_ = "";
        name_ = "";
        maybeTypeName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new ResourceHandle();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return org.tensorflow.framework.ResourceHandleProto.internal_static_tensorflow_ResourceHandle_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return org.tensorflow.framework.ResourceHandleProto.internal_static_tensorflow_ResourceHandle_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.tensorflow.framework.ResourceHandle.class,
                        org.tensorflow.framework.ResourceHandle.Builder.class);
    }

    public static final int DEVICE_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object device_ = "";

    /**
     * <pre>
     * Unique name for the device containing the resource.
     * </pre>
     *
     * <code>string device = 1;</code>
     *
     * @return The device.
     */
    @java.lang.Override
    public java.lang.String getDevice() {
        java.lang.Object ref = device_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            device_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * Unique name for the device containing the resource.
     * </pre>
     *
     * <code>string device = 1;</code>
     *
     * @return The bytes for device.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getDeviceBytes() {
        java.lang.Object ref = device_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            device_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int CONTAINER_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object container_ = "";

    /**
     * <pre>
     * Container in which this resource is placed.
     * </pre>
     *
     * <code>string container = 2;</code>
     *
     * @return The container.
     */
    @java.lang.Override
    public java.lang.String getContainer() {
        java.lang.Object ref = container_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            container_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * Container in which this resource is placed.
     * </pre>
     *
     * <code>string container = 2;</code>
     *
     * @return The bytes for container.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getContainerBytes() {
        java.lang.Object ref = container_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            container_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";

    /**
     * <pre>
     * Unique name of this resource.
     * </pre>
     *
     * <code>string name = 3;</code>
     *
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * Unique name of this resource.
     * </pre>
     *
     * <code>string name = 3;</code>
     *
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            name_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int HASH_CODE_FIELD_NUMBER = 4;
    private long hashCode_ = 0L;

    /**
     * <pre>
     * Hash code for the type of the resource. Is only valid in the same device
     * and in the same execution.
     * </pre>
     *
     * <code>uint64 hash_code = 4;</code>
     *
     * @return The hashCode.
     */
    @java.lang.Override
    public long getHashCode() {
        return hashCode_;
    }

    public static final int MAYBE_TYPE_NAME_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object maybeTypeName_ = "";

    /**
     * <pre>
     * For debug-only, the name of the type pointed to by this handle, if
     * available.
     * </pre>
     *
     * <code>string maybe_type_name = 5;</code>
     *
     * @return The maybeTypeName.
     */
    @java.lang.Override
    public java.lang.String getMaybeTypeName() {
        java.lang.Object ref = maybeTypeName_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            maybeTypeName_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * For debug-only, the name of the type pointed to by this handle, if
     * available.
     * </pre>
     *
     * <code>string maybe_type_name = 5;</code>
     *
     * @return The bytes for maybeTypeName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
    getMaybeTypeNameBytes() {
        java.lang.Object ref = maybeTypeName_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            maybeTypeName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(device_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, device_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(container_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, container_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
        }
        if (hashCode_ != 0L) {
            output.writeUInt64(4, hashCode_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(maybeTypeName_)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, maybeTypeName_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(device_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, device_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(container_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, container_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
        }
        if (hashCode_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeUInt64Size(4, hashCode_);
        }
        if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(maybeTypeName_)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, maybeTypeName_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof org.tensorflow.framework.ResourceHandle)) {
            return super.equals(obj);
        }
        org.tensorflow.framework.ResourceHandle other = (org.tensorflow.framework.ResourceHandle) obj;

        if (!getDevice()
                .equals(other.getDevice())) return false;
        if (!getContainer()
                .equals(other.getContainer())) return false;
        if (!getName()
                .equals(other.getName())) return false;
        if (getHashCode()
            != other.getHashCode()) return false;
        if (!getMaybeTypeName()
                .equals(other.getMaybeTypeName())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + DEVICE_FIELD_NUMBER;
        hash = (53 * hash) + getDevice().hashCode();
        hash = (37 * hash) + CONTAINER_FIELD_NUMBER;
        hash = (53 * hash) + getContainer().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + HASH_CODE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getHashCode());
        hash = (37 * hash) + MAYBE_TYPE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getMaybeTypeName().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static org.tensorflow.framework.ResourceHandle parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.tensorflow.framework.ResourceHandle parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.tensorflow.framework.ResourceHandle parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.tensorflow.framework.ResourceHandle parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.tensorflow.framework.ResourceHandle parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.tensorflow.framework.ResourceHandle parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.tensorflow.framework.ResourceHandle parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.tensorflow.framework.ResourceHandle parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.tensorflow.framework.ResourceHandle parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.tensorflow.framework.ResourceHandle parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.tensorflow.framework.ResourceHandle parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.tensorflow.framework.ResourceHandle parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {return newBuilder();}

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(org.tensorflow.framework.ResourceHandle prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * <pre>
     * Protocol buffer representing a handle to a tensorflow resource. Handles are
     * not valid across executions, but can be serialized back and forth from within
     * a single run.
     * </pre>
     * <p>
     * Protobuf type {@code tensorflow.ResourceHandle}
     */
    public static final class Builder extends
                                      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                                                                                              // @@protoc_insertion_point(builder_implements:tensorflow.ResourceHandle)
                                                                                                      org.tensorflow.framework.ResourceHandleOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.tensorflow.framework.ResourceHandleProto.internal_static_tensorflow_ResourceHandle_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.tensorflow.framework.ResourceHandleProto.internal_static_tensorflow_ResourceHandle_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.tensorflow.framework.ResourceHandle.class,
                            org.tensorflow.framework.ResourceHandle.Builder.class);
        }

        // Construct using org.tensorflow.framework.ResourceHandle.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);

        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            device_ = "";
            container_ = "";
            name_ = "";
            hashCode_ = 0L;
            maybeTypeName_ = "";
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return org.tensorflow.framework.ResourceHandleProto.internal_static_tensorflow_ResourceHandle_descriptor;
        }

        @java.lang.Override
        public org.tensorflow.framework.ResourceHandle getDefaultInstanceForType() {
            return org.tensorflow.framework.ResourceHandle.getDefaultInstance();
        }

        @java.lang.Override
        public org.tensorflow.framework.ResourceHandle build() {
            org.tensorflow.framework.ResourceHandle result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public org.tensorflow.framework.ResourceHandle buildPartial() {
            org.tensorflow.framework.ResourceHandle result = new org.tensorflow.framework.ResourceHandle(this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(org.tensorflow.framework.ResourceHandle result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.device_ = device_;
            }
            if (((from_bitField0_ & 0x00000002) != 0)) {
                result.container_ = container_;
            }
            if (((from_bitField0_ & 0x00000004) != 0)) {
                result.name_ = name_;
            }
            if (((from_bitField0_ & 0x00000008) != 0)) {
                result.hashCode_ = hashCode_;
            }
            if (((from_bitField0_ & 0x00000010) != 0)) {
                result.maybeTypeName_ = maybeTypeName_;
            }
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof org.tensorflow.framework.ResourceHandle) {
                return mergeFrom((org.tensorflow.framework.ResourceHandle) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(org.tensorflow.framework.ResourceHandle other) {
            if (other == org.tensorflow.framework.ResourceHandle.getDefaultInstance()) return this;
            if (!other.getDevice().isEmpty()) {
                device_ = other.device_;
                bitField0_ |= 0x00000001;
                onChanged();
            }
            if (!other.getContainer().isEmpty()) {
                container_ = other.container_;
                bitField0_ |= 0x00000002;
                onChanged();
            }
            if (!other.getName().isEmpty()) {
                name_ = other.name_;
                bitField0_ |= 0x00000004;
                onChanged();
            }
            if (other.getHashCode() != 0L) {
                setHashCode(other.getHashCode());
            }
            if (!other.getMaybeTypeName().isEmpty()) {
                maybeTypeName_ = other.maybeTypeName_;
                bitField0_ |= 0x00000010;
                onChanged();
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            device_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        case 18: {
                            container_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000002;
                            break;
                        } // case 18
                        case 26: {
                            name_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000004;
                            break;
                        } // case 26
                        case 32: {
                            hashCode_ = input.readUInt64();
                            bitField0_ |= 0x00000008;
                            break;
                        } // case 32
                        case 42: {
                            maybeTypeName_ = input.readStringRequireUtf8();
                            bitField0_ |= 0x00000010;
                            break;
                        } // case 42
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private java.lang.Object device_ = "";

        /**
         * <pre>
         * Unique name for the device containing the resource.
         * </pre>
         *
         * <code>string device = 1;</code>
         *
         * @return The device.
         */
        public java.lang.String getDevice() {
            java.lang.Object ref = device_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                device_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * Unique name for the device containing the resource.
         * </pre>
         *
         * <code>string device = 1;</code>
         *
         * @return The bytes for device.
         */
        public com.google.protobuf.ByteString
        getDeviceBytes() {
            java.lang.Object ref = device_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                device_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * Unique name for the device containing the resource.
         * </pre>
         *
         * <code>string device = 1;</code>
         *
         * @param value The device to set.
         * @return This builder for chaining.
         */
        public Builder setDevice(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            device_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Unique name for the device containing the resource.
         * </pre>
         *
         * <code>string device = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearDevice() {
            device_ = getDefaultInstance().getDevice();
            bitField0_ = (bitField0_ & ~0x00000001);
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Unique name for the device containing the resource.
         * </pre>
         *
         * <code>string device = 1;</code>
         *
         * @param value The bytes for device to set.
         * @return This builder for chaining.
         */
        public Builder setDeviceBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            device_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        private java.lang.Object container_ = "";

        /**
         * <pre>
         * Container in which this resource is placed.
         * </pre>
         *
         * <code>string container = 2;</code>
         *
         * @return The container.
         */
        public java.lang.String getContainer() {
            java.lang.Object ref = container_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                container_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * Container in which this resource is placed.
         * </pre>
         *
         * <code>string container = 2;</code>
         *
         * @return The bytes for container.
         */
        public com.google.protobuf.ByteString
        getContainerBytes() {
            java.lang.Object ref = container_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                container_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * Container in which this resource is placed.
         * </pre>
         *
         * <code>string container = 2;</code>
         *
         * @param value The container to set.
         * @return This builder for chaining.
         */
        public Builder setContainer(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            container_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Container in which this resource is placed.
         * </pre>
         *
         * <code>string container = 2;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearContainer() {
            container_ = getDefaultInstance().getContainer();
            bitField0_ = (bitField0_ & ~0x00000002);
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Container in which this resource is placed.
         * </pre>
         *
         * <code>string container = 2;</code>
         *
         * @param value The bytes for container to set.
         * @return This builder for chaining.
         */
        public Builder setContainerBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            container_ = value;
            bitField0_ |= 0x00000002;
            onChanged();
            return this;
        }

        private java.lang.Object name_ = "";

        /**
         * <pre>
         * Unique name of this resource.
         * </pre>
         *
         * <code>string name = 3;</code>
         *
         * @return The name.
         */
        public java.lang.String getName() {
            java.lang.Object ref = name_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                name_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * Unique name of this resource.
         * </pre>
         *
         * <code>string name = 3;</code>
         *
         * @return The bytes for name.
         */
        public com.google.protobuf.ByteString
        getNameBytes() {
            java.lang.Object ref = name_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                name_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * Unique name of this resource.
         * </pre>
         *
         * <code>string name = 3;</code>
         *
         * @param value The name to set.
         * @return This builder for chaining.
         */
        public Builder setName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            name_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Unique name of this resource.
         * </pre>
         *
         * <code>string name = 3;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearName() {
            name_ = getDefaultInstance().getName();
            bitField0_ = (bitField0_ & ~0x00000004);
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Unique name of this resource.
         * </pre>
         *
         * <code>string name = 3;</code>
         *
         * @param value The bytes for name to set.
         * @return This builder for chaining.
         */
        public Builder setNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            name_ = value;
            bitField0_ |= 0x00000004;
            onChanged();
            return this;
        }

        private long hashCode_;

        /**
         * <pre>
         * Hash code for the type of the resource. Is only valid in the same device
         * and in the same execution.
         * </pre>
         *
         * <code>uint64 hash_code = 4;</code>
         *
         * @return The hashCode.
         */
        @java.lang.Override
        public long getHashCode() {
            return hashCode_;
        }

        /**
         * <pre>
         * Hash code for the type of the resource. Is only valid in the same device
         * and in the same execution.
         * </pre>
         *
         * <code>uint64 hash_code = 4;</code>
         *
         * @param value The hashCode to set.
         * @return This builder for chaining.
         */
        public Builder setHashCode(long value) {

            hashCode_ = value;
            bitField0_ |= 0x00000008;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Hash code for the type of the resource. Is only valid in the same device
         * and in the same execution.
         * </pre>
         *
         * <code>uint64 hash_code = 4;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearHashCode() {
            bitField0_ = (bitField0_ & ~0x00000008);
            hashCode_ = 0L;
            onChanged();
            return this;
        }

        private java.lang.Object maybeTypeName_ = "";

        /**
         * <pre>
         * For debug-only, the name of the type pointed to by this handle, if
         * available.
         * </pre>
         *
         * <code>string maybe_type_name = 5;</code>
         *
         * @return The maybeTypeName.
         */
        public java.lang.String getMaybeTypeName() {
            java.lang.Object ref = maybeTypeName_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                maybeTypeName_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * For debug-only, the name of the type pointed to by this handle, if
         * available.
         * </pre>
         *
         * <code>string maybe_type_name = 5;</code>
         *
         * @return The bytes for maybeTypeName.
         */
        public com.google.protobuf.ByteString
        getMaybeTypeNameBytes() {
            java.lang.Object ref = maybeTypeName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                maybeTypeName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * For debug-only, the name of the type pointed to by this handle, if
         * available.
         * </pre>
         *
         * <code>string maybe_type_name = 5;</code>
         *
         * @param value The maybeTypeName to set.
         * @return This builder for chaining.
         */
        public Builder setMaybeTypeName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            maybeTypeName_ = value;
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * For debug-only, the name of the type pointed to by this handle, if
         * available.
         * </pre>
         *
         * <code>string maybe_type_name = 5;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearMaybeTypeName() {
            maybeTypeName_ = getDefaultInstance().getMaybeTypeName();
            bitField0_ = (bitField0_ & ~0x00000010);
            onChanged();
            return this;
        }

        /**
         * <pre>
         * For debug-only, the name of the type pointed to by this handle, if
         * available.
         * </pre>
         *
         * <code>string maybe_type_name = 5;</code>
         *
         * @param value The bytes for maybeTypeName to set.
         * @return This builder for chaining.
         */
        public Builder setMaybeTypeNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);
            maybeTypeName_ = value;
            bitField0_ |= 0x00000010;
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:tensorflow.ResourceHandle)
    }

    // @@protoc_insertion_point(class_scope:tensorflow.ResourceHandle)
    private static final org.tensorflow.framework.ResourceHandle DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new org.tensorflow.framework.ResourceHandle();
    }

    public static org.tensorflow.framework.ResourceHandle getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResourceHandle>
            PARSER = new com.google.protobuf.AbstractParser<ResourceHandle>() {
        @java.lang.Override
        public ResourceHandle parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<ResourceHandle> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResourceHandle> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public org.tensorflow.framework.ResourceHandle getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

