// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow/core/protobuf/meta_graph.proto

package org.tensorflow.framework;

public interface TensorInfoOrBuilder extends
                                     // @@protoc_insertion_point(interface_extends:tensorflow.TensorInfo)
                                             com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     *
     * @return The name.
     */
    java.lang.String getName();

    /**
     * <code>string name = 1;</code>
     *
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
    getNameBytes();

    /**
     * <code>.tensorflow.DataType dtype = 2;</code>
     *
     * @return The enum numeric value on the wire for dtype.
     */
    int getDtypeValue();

    /**
     * <code>.tensorflow.DataType dtype = 2;</code>
     *
     * @return The dtype.
     */
    org.tensorflow.framework.DataType getDtype();

    /**
     * <code>.tensorflow.TensorShapeProto tensor_shape = 3;</code>
     *
     * @return Whether the tensorShape field is set.
     */
    boolean hasTensorShape();

    /**
     * <code>.tensorflow.TensorShapeProto tensor_shape = 3;</code>
     *
     * @return The tensorShape.
     */
    org.tensorflow.framework.TensorShapeProto getTensorShape();

    /**
     * <code>.tensorflow.TensorShapeProto tensor_shape = 3;</code>
     */
    org.tensorflow.framework.TensorShapeProtoOrBuilder getTensorShapeOrBuilder();
}
