// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: request/grpc/proto/torchserve/inference.proto

package org.pytorch.serve.grpc.inference;

/**
 * Protobuf type {@code org.pytorch.serve.grpc.inference.PredictionResponse}
 */
public final class PredictionResponse extends
                                      com.google.protobuf.GeneratedMessageV3 implements
                                                                             // @@protoc_insertion_point(message_implements:org.pytorch.serve.grpc.inference.PredictionResponse)
                                                                                     PredictionResponseOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use PredictionResponse.newBuilder() to construct.
    private PredictionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private PredictionResponse() {
        prediction_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
            UnusedPrivateParameter unused) {
        return new PredictionResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_PredictionResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_PredictionResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        org.pytorch.serve.grpc.inference.PredictionResponse.class,
                        org.pytorch.serve.grpc.inference.PredictionResponse.Builder.class);
    }

    public static final int PREDICTION_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString prediction_ = com.google.protobuf.ByteString.EMPTY;

    /**
     * <pre>
     * Response content for prediction
     * </pre>
     *
     * <code>bytes prediction = 1;</code>
     *
     * @return The prediction.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPrediction() {
        return prediction_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!prediction_.isEmpty()) {
            output.writeBytes(1, prediction_);
        }
        getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!prediction_.isEmpty()) {
            size += com.google.protobuf.CodedOutputStream
                    .computeBytesSize(1, prediction_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof org.pytorch.serve.grpc.inference.PredictionResponse)) {
            return super.equals(obj);
        }
        org.pytorch.serve.grpc.inference.PredictionResponse other = (org.pytorch.serve.grpc.inference.PredictionResponse) obj;

        if (!getPrediction()
                .equals(other.getPrediction())) return false;
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + PREDICTION_FIELD_NUMBER;
        hash = (53 * hash) + getPrediction().hashCode();
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static org.pytorch.serve.grpc.inference.PredictionResponse parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.pytorch.serve.grpc.inference.PredictionResponse parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.pytorch.serve.grpc.inference.PredictionResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.pytorch.serve.grpc.inference.PredictionResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.pytorch.serve.grpc.inference.PredictionResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static org.pytorch.serve.grpc.inference.PredictionResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static org.pytorch.serve.grpc.inference.PredictionResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.pytorch.serve.grpc.inference.PredictionResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.pytorch.serve.grpc.inference.PredictionResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.pytorch.serve.grpc.inference.PredictionResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.pytorch.serve.grpc.inference.PredictionResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static org.pytorch.serve.grpc.inference.PredictionResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {return newBuilder();}

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(org.pytorch.serve.grpc.inference.PredictionResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code org.pytorch.serve.grpc.inference.PredictionResponse}
     */
    public static final class Builder extends
                                      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
                                                                                              // @@protoc_insertion_point(builder_implements:org.pytorch.serve.grpc.inference.PredictionResponse)
                                                                                                      org.pytorch.serve.grpc.inference.PredictionResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_PredictionResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_PredictionResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            org.pytorch.serve.grpc.inference.PredictionResponse.class,
                            org.pytorch.serve.grpc.inference.PredictionResponse.Builder.class);
        }

        // Construct using org.pytorch.serve.grpc.inference.PredictionResponse.newBuilder()
        private Builder() {

        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);

        }

        @java.lang.Override
        public Builder clear() {
            super.clear();
            bitField0_ = 0;
            prediction_ = com.google.protobuf.ByteString.EMPTY;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return org.pytorch.serve.grpc.inference.Inference.internal_static_org_pytorch_serve_grpc_inference_PredictionResponse_descriptor;
        }

        @java.lang.Override
        public org.pytorch.serve.grpc.inference.PredictionResponse getDefaultInstanceForType() {
            return org.pytorch.serve.grpc.inference.PredictionResponse.getDefaultInstance();
        }

        @java.lang.Override
        public org.pytorch.serve.grpc.inference.PredictionResponse build() {
            org.pytorch.serve.grpc.inference.PredictionResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public org.pytorch.serve.grpc.inference.PredictionResponse buildPartial() {
            org.pytorch.serve.grpc.inference.PredictionResponse result = new org.pytorch.serve.grpc.inference.PredictionResponse(
                    this);
            if (bitField0_ != 0) {
                buildPartial0(result);
            }
            onBuilt();
            return result;
        }

        private void buildPartial0(org.pytorch.serve.grpc.inference.PredictionResponse result) {
            int from_bitField0_ = bitField0_;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                result.prediction_ = prediction_;
            }
        }

        @java.lang.Override
        public Builder clone() {
            return super.clone();
        }

        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof org.pytorch.serve.grpc.inference.PredictionResponse) {
                return mergeFrom((org.pytorch.serve.grpc.inference.PredictionResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(org.pytorch.serve.grpc.inference.PredictionResponse other) {
            if (other == org.pytorch.serve.grpc.inference.PredictionResponse.getDefaultInstance()) return this;
            if (other.getPrediction() != com.google.protobuf.ByteString.EMPTY) {
                setPrediction(other.getPrediction());
            }
            this.mergeUnknownFields(other.getUnknownFields());
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            if (extensionRegistry == null) {
                throw new java.lang.NullPointerException();
            }
            try {
                boolean done = false;
                while (!done) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            done = true;
                            break;
                        case 10: {
                            prediction_ = input.readBytes();
                            bitField0_ |= 0x00000001;
                            break;
                        } // case 10
                        default: {
                            if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                                done = true; // was an endgroup tag
                            }
                            break;
                        } // default:
                    } // switch (tag)
                } // while (!done)
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.unwrapIOException();
            } finally {
                onChanged();
            } // finally
            return this;
        }

        private int bitField0_;

        private com.google.protobuf.ByteString prediction_ = com.google.protobuf.ByteString.EMPTY;

        /**
         * <pre>
         * Response content for prediction
         * </pre>
         *
         * <code>bytes prediction = 1;</code>
         *
         * @return The prediction.
         */
        @java.lang.Override
        public com.google.protobuf.ByteString getPrediction() {
            return prediction_;
        }

        /**
         * <pre>
         * Response content for prediction
         * </pre>
         *
         * <code>bytes prediction = 1;</code>
         *
         * @param value The prediction to set.
         * @return This builder for chaining.
         */
        public Builder setPrediction(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            prediction_ = value;
            bitField0_ |= 0x00000001;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * Response content for prediction
         * </pre>
         *
         * <code>bytes prediction = 1;</code>
         *
         * @return This builder for chaining.
         */
        public Builder clearPrediction() {
            bitField0_ = (bitField0_ & ~0x00000001);
            prediction_ = getDefaultInstance().getPrediction();
            onChanged();
            return this;
        }

        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:org.pytorch.serve.grpc.inference.PredictionResponse)
    }

    // @@protoc_insertion_point(class_scope:org.pytorch.serve.grpc.inference.PredictionResponse)
    private static final org.pytorch.serve.grpc.inference.PredictionResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new org.pytorch.serve.grpc.inference.PredictionResponse();
    }

    public static org.pytorch.serve.grpc.inference.PredictionResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PredictionResponse>
            PARSER = new com.google.protobuf.AbstractParser<PredictionResponse>() {
        @java.lang.Override
        public PredictionResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            Builder builder = newBuilder();
            try {
                builder.mergeFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                throw e.setUnfinishedMessage(builder.buildPartial());
            } catch (com.google.protobuf.UninitializedMessageException e) {
                throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
            } catch (java.io.IOException e) {
                throw new com.google.protobuf.InvalidProtocolBufferException(e)
                        .setUnfinishedMessage(builder.buildPartial());
            }
            return builder.buildPartial();
        }
    };

    public static com.google.protobuf.Parser<PredictionResponse> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PredictionResponse> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public org.pytorch.serve.grpc.inference.PredictionResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}
