version: '3.3'
services:
  standalone:
    build:
      context: ../../.
      dockerfile: docker/standalone/Dockerfile
    image: crayfish-standalone
    container_name: 'crayfish-standalone'
    working_dir: /home/user/crayfish
    volumes:
      - ../../logs:/home/user/crayfish/logs
      - ../../results-standalone:/home/user/crayfish/results-standalone